# Site settings
title: image555小屋
email: 948694935@qq.com
description: > # this means to ignore newlines until "baseurl:"
url: http://image555.github.io # the base hostname & protocol for your site

twitter_username:
github_username: image555



baseurl:  #http://image555.github.io

host: 192.168.116.61 #监听网址
port: 4000 #监听端口

author: image555
authorUrl: http://image555.github.io

permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"] #过滤这些文件


paginate: 10 #分页
paginate_path: "page:num"#分页设置

widgets:
- category
- tag
- links
- douban
- rss

# Build settings
markdown: kramdown


gems: [jekyll-paginate]
